<?php

declare(strict_types=1);

namespace ApplicationLogger\Bundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Configuration schema for ApplicationLogger bundle.
 *
 * Defines all available configuration options with secure defaults.
 * Focus on resilience: short timeouts, circuit breaker enabled by default.
 */
class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('application_logger');
        $rootNode = $treeBuilder->getRootNode();

        // @phpstan-ignore-next-line
        $rootNode
            ->children()
                // Core configuration
                ->scalarNode('dsn')
                    ->isRequired()
                    ->cannotBeEmpty()
                    ->info('Data Source Name - Project endpoint URL (format: https://host/project-id)')
                ->end()
                ->scalarNode('api_key')
                    ->isRequired()
                    ->cannotBeEmpty()
                    ->info('API Key for authentication (sent as X-Api-Key header)')
                ->end()
                ->booleanNode('enabled')
                    ->defaultTrue()
                    ->info('Enable/disable error tracking globally')
                ->end()
                ->scalarNode('release')
                    ->defaultNull()
                    ->info('Application version/release identifier')
                ->end()
                ->scalarNode('environment')
                    ->defaultValue('production')
                    ->info('Environment name (production, staging, development)')
                ->end()

                // Performance & Resilience
                ->floatNode('timeout')
                    ->defaultValue(2.0)
                    ->min(0.5)
                    ->max(5.0)
                    ->info('Maximum timeout for API requests in seconds (default: 2s for resilience)')
                ->end()
                ->integerNode('retry_attempts')
                    ->defaultValue(0)
                    ->min(0)
                    ->max(3)
                    ->info('Number of retry attempts (0 = fail fast, recommended for resilience)')
                ->end()

                // Circuit Breaker Configuration
                ->arrayNode('circuit_breaker')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('Enable circuit breaker pattern to prevent cascade failures')
                        ->end()
                        ->integerNode('failure_threshold')
                            ->defaultValue(5)
                            ->min(1)
                            ->info('Number of consecutive failures before opening circuit')
                        ->end()
                        ->integerNode('timeout')
                            ->defaultValue(60)
                            ->min(10)
                            ->info('Time in seconds to keep circuit open after opening')
                        ->end()
                        ->integerNode('half_open_attempts')
                            ->defaultValue(1)
                            ->min(1)
                            ->info('Number of test requests allowed in half-open state')
                        ->end()
                    ->end()
                ->end()

                // Capture Settings
                ->scalarNode('capture_level')
                    ->defaultValue('error')
                    ->info('Minimum Monolog level to capture (debug, info, notice, warning, error, critical, alert, emergency)')
                ->end()
                ->arrayNode('scrub_fields')
                    ->prototype('scalar')->end()
                    ->defaultValue(['password', 'token', 'api_key', 'secret', 'authorization'])
                    ->info('Field names to scrub from requests (security)')
                ->end()
                ->integerNode('max_breadcrumbs')
                    ->defaultValue(50)
                    ->min(10)
                    ->max(100)
                    ->info('Maximum number of breadcrumbs to track')
                ->end()

                // JavaScript SDK Configuration
                ->arrayNode('javascript')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('Enable JavaScript SDK integration and error tracking')
                        ->end()
                        ->booleanNode('auto_inject')
                            ->defaultTrue()
                            ->info('Automatically inject JavaScript SDK on all HTML pages')
                        ->end()
                        ->booleanNode('debug')
                            ->defaultFalse()
                            ->info('Enable JavaScript SDK debug mode (console.log)')
                        ->end()
                        ->scalarNode('environment')
                            ->defaultNull()
                            ->info('Environment name for JavaScript errors (defaults to kernel.environment)')
                        ->end()
                        ->scalarNode('release')
                            ->defaultNull()
                            ->info('Release version for JavaScript errors (defaults to root release config)')
                        ->end()
                        ->arrayNode('scrub_fields')
                            ->prototype('scalar')->end()
                            ->defaultValue([])
                            ->info('Additional fields to scrub in JavaScript errors (merged with root scrub_fields)')
                        ->end()
                    ->end()
                ->end()

                // Session Tracking Configuration
                ->arrayNode('session_tracking')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('Enable automatic session tracking (required for session replay)')
                        ->end()
                        ->booleanNode('track_page_views')
                            ->defaultTrue()
                            ->info('Automatically track page views as session events')
                        ->end()
                        ->integerNode('idle_timeout')
                            ->defaultValue(1800)
                            ->min(300)
                            ->max(7200)
                            ->info('Session idle timeout in seconds (default: 30 minutes)')
                        ->end()
                        ->arrayNode('ignored_routes')
                            ->prototype('scalar')->end()
                            ->defaultValue(['_profiler', '_wdt'])
                            ->info('Route names to ignore for session tracking')
                        ->end()
                        ->arrayNode('ignored_paths')
                            ->prototype('scalar')->end()
                            ->defaultValue(['/api/', '/_fragment'])
                            ->info('URL paths to ignore for session tracking (prefix match)')
                        ->end()
                    ->end()
                ->end()

                // Session Replay Configuration
                ->arrayNode('session_replay')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('Enable session replay recording (error-triggered only)')
                        ->end()
                        ->integerNode('buffer_before_error_seconds')
                            ->defaultValue(30)
                            ->min(5)
                            ->max(60)
                            ->info('Buffer seconds BEFORE error (default: 30s, max: 60s)')
                        ->end()
                        ->integerNode('buffer_before_error_clicks')
                            ->defaultValue(10)
                            ->min(1)
                            ->max(15)
                            ->info('Buffer clicks BEFORE error (default: 10, max: 15)')
                        ->end()
                        ->integerNode('buffer_after_error_seconds')
                            ->defaultValue(30)
                            ->min(5)
                            ->max(60)
                            ->info('Buffer seconds AFTER error (default: 30s, max: 60s)')
                        ->end()
                        ->integerNode('buffer_after_error_clicks')
                            ->defaultValue(10)
                            ->min(1)
                            ->max(15)
                            ->info('Buffer clicks AFTER error (default: 10, max: 15)')
                        ->end()
                        ->integerNode('snapshot_throttle_ms')
                            ->defaultValue(1000)
                            ->min(500)
                            ->max(5000)
                            ->info('DOM snapshot throttle in milliseconds (default: 1000ms, min: 500ms)')
                        ->end()
                        ->integerNode('click_debounce_ms')
                            ->defaultValue(1000)
                            ->min(100)
                            ->max(5000)
                            ->info('Click event debounce in milliseconds - prevents spam from rapid clicking (default: 1000ms, min: 100ms)')
                        ->end()
                        ->integerNode('max_snapshot_size')
                            ->defaultValue(1048576)
                            ->min(102400)
                            ->max(5242880)
                            ->info('Maximum snapshot size in bytes (default: 1MB, max: 5MB)')
                        ->end()
                        ->integerNode('session_timeout_minutes')
                            ->defaultValue(30)
                            ->min(5)
                            ->max(120)
                            ->info('Cross-page session timeout in minutes (default: 30, max: 120)')
                        ->end()
                        ->integerNode('max_buffer_size_mb')
                            ->defaultValue(5)
                            ->min(1)
                            ->max(20)
                            ->info('Maximum localStorage buffer size in MB (default: 5MB, max: 20MB)')
                        ->end()
                        ->booleanNode('expose_api')
                            ->defaultTrue()
                            ->info('Expose JavaScript API for user control (enable/disable/isEnabled)')
                        ->end()
                    ->end()
                ->end()

                // Advanced Options
                ->booleanNode('async')
                    ->defaultTrue()
                    ->info('Use async HTTP client (fire-and-forget for maximum resilience)')
                ->end()
                ->booleanNode('debug')
                    ->defaultFalse()
                    ->info('Enable PHP debug logging')
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}
