<?php

declare(strict_types=1);

namespace ApplicationLogger\Bundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Configuration schema for ApplicationLogger bundle.
 *
 * Defines all available configuration options with secure defaults.
 * Focus on resilience: short timeouts, circuit breaker enabled by default.
 */
class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('application_logger');
        $rootNode = $treeBuilder->getRootNode();

        // @phpstan-ignore-next-line
        $rootNode
            ->children()
                // Core configuration
                // Empty (not required) by design: a clean `composer require` whose
                // Flex recipe was skipped/auto-generated leaves the bundle enabled
                // with NO config. Requiring these here would fail `cache:clear` and
                // break the host application (resilience rule #1). An empty DSN keeps
                // the bundle inert at runtime (ApiClient no-ops; see parseDsnEndpoint).
                ->scalarNode('dsn')
                    ->defaultValue('')
                    ->info('Data Source Name - Project endpoint URL (format: https://host/project-id). Empty = bundle stays inert.')
                ->end()
                ->scalarNode('api_key')
                    ->defaultValue('')
                    ->info('API Key for authentication (sent as X-Api-Key header). Empty = bundle stays inert.')
                ->end()
                ->booleanNode('enabled')
                    ->defaultTrue()
                    ->info('Enable/disable error tracking globally')
                ->end()
                ->scalarNode('release')
                    ->defaultNull()
                    ->info('Application version/release identifier')
                ->end()
                ->scalarNode('environment')
                    ->defaultValue('production')
                    ->info('Environment name (production, staging, development)')
                ->end()

                // Log Aggregation (ships non-exception Monolog records to the Go log-collector)
                ->scalarNode('log_endpoint')
                    ->defaultNull()
                    ->info('Base URL of the log-collector HTTP ingestion endpoint (e.g. https://{slug}.logs.applogger.eu). When null, non-exception log records are NOT shipped to log aggregation.')
                ->end()
                ->scalarNode('log_token')
                    ->defaultNull()
                    ->info('Log ingestion token (sk_log_...) sent as X-Api-Key to the log-collector. Required for log aggregation.')
                ->end()
                ->scalarNode('log_path')
                    ->defaultValue('/v1/logs')
                    ->info('HTTP path of the single-log ingestion endpoint on the collector (batch is "<log_path>/batch")')
                ->end()
                ->integerNode('log_batch_size')
                    ->defaultValue(50)
                    ->min(1)
                    ->max(1000)
                    ->info('Maximum number of log records buffered before flushing to the collector batch endpoint (collector hard-caps batches at 1000)')
                ->end()
                ->integerNode('max_log_buffer')
                    ->defaultValue(1000)
                    ->min(1)
                    ->max(10000)
                    ->info('Hard cap on buffered log records; oldest records are dropped beyond this to bound memory')
                ->end()
                ->booleanNode('error_tracking_enabled')
                    ->defaultTrue()
                    ->info('Capture and ship exceptions/errors. Set false to run log-aggregation only.')
                ->end()
                ->booleanNode('log_aggregation_enabled')
                    ->defaultTrue()
                    ->info('Buffer and ship non-exception log records to the collector. Set false to run error-tracking only.')
                ->end()
                ->arrayNode('excluded_channels')
                    ->prototype('scalar')->end()
                    ->defaultValue(['http_client', 'console', 'deprecation', 'doctrine'])
                    ->info('Monolog channels excluded from log aggregation, in addition to the always-excluded event/request/php and the bundle internal channel. Channel NAMES only (no "!" prefix). Literal list only — NOT env-driven. Excluding a channel blocks ALL levels on it (incl. error). Set to [] to aggregate framework channels too; note re-including http_client at capture_level: info revives the self-amplification loop.')
                ->end()
                ->scalarNode('endpoint_path')
                    ->defaultValue('/api/v1/errors')
                    ->info('HTTP path of the error ingestion endpoint on the platform API')
                ->end()

                // Performance & Resilience
                ->floatNode('timeout')
                    ->defaultValue(2.0)
                    ->min(0.5)
                    ->max(5.0)
                    ->info('Maximum timeout for API requests in seconds (default: 2s for resilience)')
                ->end()
                ->floatNode('flush_budget')
                    ->defaultValue(2.0)
                    ->min(0.05)
                    ->max(2.0)
                    ->info('Wall-clock seconds the post-response telemetry drain (kernel.terminate / __destruct) may block a worker. Effective cap = min(timeout, flush_budget). Default 2.0s matches the previous hardcoded terminate cap (no delivery change). LOWER it (e.g. 0.5) to harden a FrankenPHP worker pool against a slow collector. NOTE: min()-clamped against timeout at runtime — a value above timeout is a no-op.')
                ->end()
                ->integerNode('retry_attempts')
                    ->defaultValue(0)
                    ->min(0)
                    ->max(3)
                    ->info('Number of retry attempts (0 = fail fast, recommended for resilience)')
                ->end()

                // Circuit Breaker Configuration
                ->arrayNode('circuit_breaker')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('Enable circuit breaker pattern to prevent cascade failures')
                        ->end()
                        ->integerNode('failure_threshold')
                            ->defaultValue(5)
                            ->min(1)
                            ->info('Number of consecutive failures before opening circuit')
                        ->end()
                        ->integerNode('timeout')
                            ->defaultValue(60)
                            ->min(10)
                            ->max(300)
                            ->info('Time in seconds to keep circuit open after opening (capped at 300s to keep cache TTL bounded)')
                        ->end()
                        ->integerNode('half_open_attempts')
                            ->defaultValue(1)
                            ->min(1)
                            ->info('Number of test requests allowed in half-open state')
                        ->end()
                    ->end()
                ->end()

                // Capture Settings
                // BND-08 (won't-fix, deliberate): NOT an enumNode and NO ->validate()
                // closure. Both reject %env()% placeholders at container-compile time
                // (the placeholder string is validated before env resolution), but
                // capture_level is intentionally env-driven (APPLICATION_LOGGER_CAPTURE_LEVEL)
                // and the bundle's example configs use %env()% for it. A constrained node
                // would break that. An invalid LITERAL is handled safely at runtime:
                // ApplicationLoggerHandler::__construct falls back to Level::Error on an
                // unknown level (never throws into the host). Keeping it a plain scalar
                // preserves env compatibility, which outweighs compile-time validation
                // of a value that already degrades safely.
                ->scalarNode('capture_level')
                    ->defaultValue('error')
                    ->cannotBeEmpty()
                    ->info('Minimum Monolog level to capture (debug, info, notice, warning, error, critical, alert, emergency)')
                ->end()
                ->arrayNode('scrub_fields')
                    ->prototype('scalar')->end()
                    // KEEP IN SYNC with the canonical JS scrub list in
                    // assets/src/scrub-fields.js (DEFAULT_SCRUB_FIELDS). The two
                    // lists cannot share a runtime value (PHP vs JS), so a field
                    // added on one side MUST be mirrored on the other.
                    ->defaultValue(['password', 'token', 'api_key', 'secret', 'authorization', 'credit_card', 'creditcard', 'card_number', 'cvv', 'ssn', 'iban'])
                    ->info('Field names to scrub from requests (security). Keep in sync with assets/src/scrub-fields.js.')
                ->end()
                ->integerNode('max_breadcrumbs')
                    ->defaultValue(50)
                    ->min(10)
                    ->max(100)
                    ->info('Maximum number of breadcrumbs to track')
                ->end()

                // JavaScript SDK Configuration
                ->arrayNode('javascript')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('Enable JavaScript SDK integration and error tracking')
                        ->end()
                        ->booleanNode('auto_inject')
                            ->defaultTrue()
                            ->info('Automatically inject JavaScript SDK on all HTML pages')
                        ->end()
                        ->booleanNode('debug')
                            ->defaultFalse()
                            ->info('Enable JavaScript SDK debug mode (console.log)')
                        ->end()
                        ->scalarNode('environment')
                            ->defaultNull()
                            ->info('Environment name for JavaScript errors (defaults to kernel.environment)')
                        ->end()
                        ->scalarNode('release')
                            ->defaultNull()
                            ->info('Release version for JavaScript errors (defaults to root release config)')
                        ->end()
                        ->arrayNode('scrub_fields')
                            ->prototype('scalar')->end()
                            ->defaultValue([])
                            ->info('Additional fields to scrub in JavaScript errors (merged with root scrub_fields)')
                        ->end()
                    ->end()
                ->end()

                // Session Tracking Configuration
                ->arrayNode('session_tracking')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('Enable automatic session tracking (required for session replay)')
                        ->end()
                        ->booleanNode('track_page_views')
                            ->defaultTrue()
                            ->info('Automatically track page views as session events')
                        ->end()
                        ->integerNode('idle_timeout')
                            ->defaultValue(1800)
                            ->min(300)
                            ->max(7200)
                            ->info('Session idle timeout in seconds (default: 30 minutes)')
                        ->end()
                        ->arrayNode('ignored_routes')
                            ->prototype('scalar')->end()
                            ->defaultValue(['_profiler', '_wdt'])
                            ->info('Route names to ignore for session tracking')
                        ->end()
                        ->arrayNode('ignored_paths')
                            ->prototype('scalar')->end()
                            ->defaultValue(['/api/', '/_fragment'])
                            ->info('URL paths to ignore for session tracking (prefix match)')
                        ->end()
                    ->end()
                ->end()

                // Session Replay Configuration
                ->arrayNode('session_replay')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('Enable session replay recording (error-triggered only)')
                        ->end()
                        ->integerNode('buffer_before_error_seconds')
                            ->defaultValue(30)
                            ->min(5)
                            ->max(60)
                            ->info('Buffer seconds BEFORE error (default: 30s, max: 60s)')
                        ->end()
                        ->integerNode('buffer_before_error_clicks')
                            ->defaultValue(10)
                            ->min(1)
                            ->max(15)
                            ->info('Buffer clicks BEFORE error (default: 10, max: 15)')
                        ->end()
                        ->integerNode('buffer_after_error_seconds')
                            ->defaultValue(30)
                            ->min(5)
                            ->max(60)
                            ->info('Buffer seconds AFTER error (default: 30s, max: 60s)')
                        ->end()
                        ->integerNode('buffer_after_error_clicks')
                            ->defaultValue(10)
                            ->min(1)
                            ->max(15)
                            ->info('Buffer clicks AFTER error (default: 10, max: 15)')
                        ->end()
                        ->integerNode('snapshot_throttle_ms')
                            ->defaultValue(1000)
                            ->min(500)
                            ->max(5000)
                            ->info('DOM snapshot throttle in milliseconds (default: 1000ms, min: 500ms)')
                        ->end()
                        ->integerNode('click_debounce_ms')
                            ->defaultValue(1000)
                            ->min(100)
                            ->max(5000)
                            ->info('Click event debounce in milliseconds - prevents spam from rapid clicking (default: 1000ms, min: 100ms)')
                        ->end()
                        ->integerNode('max_snapshot_size')
                            ->defaultValue(1048576)
                            ->min(102400)
                            ->max(5242880)
                            ->info('Maximum snapshot size in bytes (default: 1MB, max: 5MB)')
                        ->end()
                        ->integerNode('session_timeout_minutes')
                            ->defaultValue(30)
                            ->min(5)
                            ->max(120)
                            ->info('Cross-page session timeout in minutes (default: 30, max: 120)')
                        ->end()
                        ->integerNode('max_buffer_size_mb')
                            ->defaultValue(5)
                            ->min(1)
                            ->max(20)
                            ->info('Maximum localStorage buffer size in MB (default: 5MB, max: 20MB)')
                        ->end()
                        ->booleanNode('expose_api')
                            ->defaultTrue()
                            ->info('Expose JavaScript API for user control (enable/disable/isEnabled)')
                        ->end()
                    ->end()
                ->end()

                // Advanced Options
                ->booleanNode('async')
                    ->defaultTrue()
                    ->info('Use async HTTP client (fire-and-forget for maximum resilience)')
                ->end()
                ->booleanNode('debug')
                    ->defaultFalse()
                    ->info('Enable PHP debug logging')
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}
