<?php

declare(strict_types=1);

namespace ApplicationLogger\Bundle\EventSubscriber;

use ApplicationLogger\Bundle\Twig\ApplicationLoggerExtension;
use Psr\Log\LoggerInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\ResponseEvent;
use Symfony\Component\HttpKernel\KernelEvents;

/**
 * Automatically injects ApplicationLogger JavaScript SDK into HTML responses.
 *
 * When auto_inject is enabled, this subscriber adds the JavaScript SDK
 * initialization script before the closing </body> tag of all HTML responses.
 *
 * This provides zero-configuration JavaScript error tracking - users just
 * need to install the bundle and configure the DSN.
 */
final class JavaScriptInjectionSubscriber implements EventSubscriberInterface
{
    public function __construct(
        private readonly bool $autoInject,
        private readonly bool $enabled,
        private readonly ApplicationLoggerExtension $twigExtension,
        private readonly ?LoggerInterface $logger = null,
    ) {
    }

    public static function getSubscribedEvents(): array
    {
        return [
            // Priority -10: run late, after the response content has been generated by
            // controllers/other listeners, but well before Symfony's profiler/web-debug
            // toolbar listener (-128). This keeps us out of the way of other HTML mutators
            // while still mutating a fully-rendered body.
            KernelEvents::RESPONSE => ['onKernelResponse', -10],
        ];
    }

    /**
     * Inject JavaScript SDK into HTML responses.
     *
     * Only injects when:
     * - JavaScript SDK is enabled
     * - Auto-inject is enabled
     * - It's the main request (not sub-requests)
     * - Response is HTML
     * - Response contains </body> tag
     */
    public function onKernelResponse(ResponseEvent $event): void
    {
        // Skip if JavaScript SDK is disabled
        if (!$this->enabled) {
            return;
        }

        // Skip if auto-inject is disabled
        if (!$this->autoInject) {
            return;
        }

        // Only inject on main requests (not sub-requests)
        if (!$event->isMainRequest()) {
            return;
        }

        $response = $event->getResponse();

        // Do not inject into error responses (4xx/5xx). Their error templates are
        // typically minimal and do not include the host application's importmap,
        // so the SDK's ES-module <script> would leave a bare specifier that the
        // browser cannot resolve. Error pages have no need for the client SDK.
        if ($response->getStatusCode() >= 400) {
            return;
        }

        // Only inject in HTML responses
        $contentType = $response->headers->get('Content-Type', '');
        if (!str_contains($contentType, 'text/html') && !empty($contentType)) {
            return;
        }

        $content = $response->getContent();

        // Skip if no </body> tag found (case-insensitive)
        if (false === $content || false === stripos($content, '</body>')) {
            return;
        }

        try {
            // Ask the Twig extension for the SDK scripts already separated by their
            // target DOM position. No re-parsing / magic-string sniffing required.
            $fragments = $this->twigExtension->renderFragments();

            $injected = $this->injectFragments($content, $fragments);

            // Nothing rendered (SDK disabled / invalid config) - leave response untouched.
            if (null === $injected) {
                $this->debug('JavaScript SDK script generation returned empty result');

                return;
            }

            $response->setContent($injected);
            $this->debug('Successfully injected JavaScript SDK into HTML response');
        } catch (\Throwable $e) {
            // Never throw - resilience is priority
            $this->logError('Failed to inject JavaScript SDK', [
                'exception' => $e->getMessage(),
                'file' => $e->getFile(),
                'line' => $e->getLine(),
            ]);
        }
    }

    /**
     * Inject the pre-positioned SDK fragments into HTML content.
     *
     * 3-layer defense-in-depth placement (preserved from the original behaviour):
     * 1. headStart - nuclear trap injected RIGHT AFTER <head> (earliest possible execution)
     * 2. headEnd   - buffer script injected BEFORE </head> (early, after the nuclear trap)
     * 3. bodyEnd   - module scripts injected before </body> (deferred, full SDK)
     *
     * @param array{headStart: string, headEnd: string, bodyEnd: string} $fragments
     *
     * @return string|null Modified content, or null when there is nothing to inject
     */
    private function injectFragments(string $content, array $fragments): ?string
    {
        if ('' === $fragments['headStart'] && '' === $fragments['headEnd'] && '' === $fragments['bodyEnd']) {
            return null;
        }

        // 1. Nuclear trap RIGHT AFTER <head> (earliest execution, before any head scripts).
        if ('' !== $fragments['headStart']) {
            $headOpenPos = stripos($content, '<head>');

            if (false !== $headOpenPos) {
                $insertPos = $headOpenPos + \strlen('<head>');
                $content = substr_replace($content, "\n".$fragments['headStart'], $insertPos, 0);
                $this->debug('Injected nuclear trap right after <head>');
            } else {
                $this->debug('No <head> tag found for nuclear trap injection', 'warning');
            }
        }

        // 2. Buffer script BEFORE </head> (early, after the nuclear trap).
        if ('' !== $fragments['headEnd']) {
            $headClosePos = stripos($content, '</head>');

            if (false !== $headClosePos) {
                $content = substr_replace($content, $fragments['headEnd'], $headClosePos, 0);
                $this->debug('Injected buffer script before </head>');
            } else {
                $this->debug('No </head> tag found for buffer script', 'warning');
            }
        }

        // 3. Module scripts before </body> (deferred, full SDK).
        if ('' !== $fragments['bodyEnd']) {
            $bodyPos = stripos($content, '</body>');

            if (false !== $bodyPos) {
                $content = substr_replace($content, $fragments['bodyEnd'], $bodyPos, 0);
                $this->debug('Injected module script before </body>');
            } else {
                $this->logError('Could not find </body> tag for module script injection');
            }
        }

        return $content;
    }

    /**
     * Emit a debug/warning log line if a logger is configured.
     */
    private function debug(string $message, string $level = 'debug'): void
    {
        $this->logger?->log($level, 'ApplicationLogger: '.$message);
    }

    /**
     * Log an error message.
     *
     * @param array<string, mixed> $context
     */
    private function logError(string $message, array $context = []): void
    {
        $this->logger?->error('ApplicationLogger: '.$message, $context);
    }
}
